name: base_specCNN_newData_1
#name: test_c_2
DB: data_base/PA/ASVspoof2019_PA_
DB_trn: trainspec_magnitude_2048_800_480/
DB_dev: devspec_magnitude_2048_800_480/
DB_eval: evalspec_magnitude_2048_800_480/
dir_meta_trn: cm_protocols/ASVspoof2019.PA.cm.train.trn.txt
dir_meta_dev: cm_protocols/ASVspoof2019.PA.cm.dev.trl.txt
dir_meta_eval: cm_protocols/ASVspoof2019.PA.cm.eval.trl.txt
gpu_idx: [0] #[0, 1]
nb_proc_db: 4
save_dir: /exp/model/networks/
optimizer: Adam #sgd
lr: 0.0005
opt_mom: 0.9
wd: 0.0001
epoch: 100
batch_size: 32
nb_time: 120
feat_dim: 1025
c_loss_weight: 0.00005
c_loss_lr: 0.5

#flags
comet_disable: 1
nesterov: 0 #for sgd optim
amsgrad: 1 #for adam optim
save_best_only: 0


#model-related
model:
  in_channels: 1
  filts: [16, [16, 32], [32, 64], [64, 64], [64, 128], [128, 128]]
  kernels: [[3, 7], [3, 7], [3, 7], [3, 7], [3, 7], [3, 7]]
  strides: [1, 1, [2, 4], [2, 4], [2, 4], [2, 4]]
  blocks: [1, 2, 2, 2]
  nb_fc_node: 64 #4096 #64
  nb_classes: 2
